title: Welcome to lwlOS
properties:
  mode: "run-once"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to lwlOS"
      icon: "/usr/share/fedora-logos/fedora_darkbackground.svg"
      description: |
        A custom distro tailored for laptops from Laptop With Linux.
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: true
        system: false
      groups:
        Additional Software:
          description: Additional applications
          default: false
          packages:
             - Firefox: org.mozilla.firefox
             - Thunderbird: org.mozilla.Thunderbird
             - LibreOffice: org.libreoffice.LibreOffice
             - Brave Browser: com.brave.Browser
             - Gimp: org.gimp.GIMP
             - Skype: com.skype.Client
             - VLC: org.videolan.VLC
             - Audacity: org.audacityteam.Audacity
             - Steam: com.valvesoftware.Steam
             - Spotify: com.spotify.Client
             - PuTTY: uk.org.greenend.chiark.sgtatham.putty
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/usr/share/fedora-logos/fedora_darkbackground.svg"
      links:
        - "Install More Applications":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://laptopwithlinux.com
      description: |
        Thanks for setting up lwlOS, we hope you enjoy it!