title: Welcome to lwlOS
properties:
  mode: "run-once"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to lwlOS"
      icon: "/path/to/icon"
      description: |
        ATTENTION!
        Please wait for notification that all flatpaks are installed before proceeding!

        Explore useful apps and options!
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: true
        system: false
      groups:
        User Apps:
          description: Additional software
          default: false
          packages:
             - Firefox: org.mozilla.firefox
             - Thunderbird: org.mozilla.Thunderbird
             - LibreOffice: org.libreoffice.LibreOffice
             - Brave Browser: com.brave.Browser
             - Gimp: org.gimp.GIMP
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://laptopwithlinux.com
      description: |
        Thanks for trying lwlOS, I hope you enjoy it!